-- =====================================================================
-- RSK ODESSA — ТРАНЗАКЦИОННЫЕ RPC И AUDIT LOG
-- Версия: 2.8.0
-- =====================================================================
-- Порядок применения:
--   1. database/migrate-v2.7-rls-finance.sql уже применён;
--   2. frontend переключён на RPC из этого файла;
--   3. только после этого применяется данный файл.
--
-- ВАЖНО: миграция удаляет временные RLS-политики прямой записи Финансиста
-- и Снабженца, а также закрывает прямой INSERT в orders/cash_requests.
-- Старый frontend после применения не сможет создавать заявки, выдавать
-- деньги и сохранять расход своей доставки напрямую.
--
-- RPC:
--   * create_order_with_items          — заявка материалов + позиции;
--   * create_cash_request_with_items   — финансовая заявка + позиции;
--   * issue_cash_request               — обе стороны выдачи + статус заявки;
--   * save_own_delivery_expense        — upsert/delete своей доставки.
--
-- Все функции SECURITY DEFINER, сами проверяют auth.uid(), активного
-- сотрудника, роль, состояние сущности и входные данные. Любая ошибка
-- откатывает всю команду вместе с записью Audit Log.
-- =====================================================================

begin;

-- =====================================================================
-- 0. ПРЕДВАРИТЕЛЬНЫЕ ПРОВЕРКИ
-- =====================================================================

do $$
begin
    if to_regprocedure('public.rsk_current_employee_id()') is null
       or to_regprocedure('public.rsk_current_employee_role()') is null then
        raise exception using
            errcode = 'P0001',
            message = 'Сначала примените database/migrate-v2.7-rls-finance.sql';
    end if;

    if to_regclass('public.orders') is null
       or to_regclass('public.order_items') is null
       or to_regclass('public.cash_requests') is null
       or to_regclass('public.cash_request_items') is null
       or to_regclass('public.cash_operations') is null then
        raise exception using
            errcode = 'P0001',
            message = 'Не найдены таблицы заявок/операций — сверьте database/schema.sql';
    end if;
end $$;

-- У одной заявки может быть только один расход своей доставки. Исторические
-- дубли автоматически не удаляем: это финансовые данные, их надо сверить.
do $$
declare
    duplicate_orders text;
begin
    select string_agg(order_id::text, ', ' order by order_id)
      into duplicate_orders
      from (
          select order_id
          from public.cash_operations
          where source = 'own_delivery'
            and order_id is not null
          group by order_id
          having count(*) > 1
      ) as duplicates;

    if duplicate_orders is not null then
        raise exception using
            errcode = 'P0001',
            message = 'Найдены дубли own_delivery для orders.id: ' || duplicate_orders,
            hint = 'Сверьте операции вручную и оставьте одну запись на заявку, затем повторите миграцию.';
    end if;
end $$;

create unique index if not exists cash_operations_one_own_delivery_per_order
    on public.cash_operations (order_id)
    where source = 'own_delivery' and order_id is not null;

-- =====================================================================
-- 1. НЕИЗМЕНЯЕМЫЙ AUDIT LOG
-- =====================================================================

create table if not exists public.audit_log (
    id                  bigint generated by default as identity primary key,
    occurred_at         timestamptz not null default clock_timestamp(),
    actor_user_id       uuid        not null,
    actor_employee_id   bigint      references public.employees(id) on delete set null,
    actor_role          text,
    action              text        not null,
    entity_type         text        not null,
    entity_id           text,
    idempotency_key     uuid        not null,
    old_data            jsonb,
    new_data            jsonb,
    metadata            jsonb       not null default '{}'::jsonb,
    transaction_id      bigint      not null default txid_current()
);

create unique index if not exists audit_log_command_once
    on public.audit_log (actor_user_id, action, idempotency_key);
create index if not exists audit_log_occurred_at_idx
    on public.audit_log (occurred_at desc);
create index if not exists audit_log_actor_idx
    on public.audit_log (actor_employee_id, occurred_at desc);
create index if not exists audit_log_entity_idx
    on public.audit_log (entity_type, entity_id, occurred_at desc);

alter table public.audit_log enable row level security;
alter table public.audit_log force row level security;

revoke all on table public.audit_log from public, anon, authenticated;
grant select on table public.audit_log to authenticated;

-- Identity sequence не выдаём authenticated: журнал пишет только definer-функция.

drop policy if exists rsk_audit_log_select on public.audit_log;
create policy rsk_audit_log_select
on public.audit_log
for select
to authenticated
using (
    public.rsk_current_employee_id() is not null
    and public.rsk_current_employee_role() in ('Администратор', 'Директор')
);

-- Внутренняя запись журнала. Клиент не получает EXECUTE.
create or replace function public.rsk_write_audit(
    p_action          text,
    p_entity_type     text,
    p_entity_id       text,
    p_idempotency_key uuid,
    p_old_data        jsonb,
    p_new_data        jsonb,
    p_metadata        jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    audit_id bigint;
begin
    if auth.uid() is null then
        raise exception using errcode = '28000', message = 'Требуется авторизация';
    end if;

    if p_idempotency_key is null then
        raise exception using errcode = '22023', message = 'idempotency_key обязателен';
    end if;

    insert into public.audit_log (
        actor_user_id,
        actor_employee_id,
        actor_role,
        action,
        entity_type,
        entity_id,
        idempotency_key,
        old_data,
        new_data,
        metadata
    ) values (
        auth.uid(),
        public.rsk_current_employee_id(),
        public.rsk_current_employee_role(),
        p_action,
        p_entity_type,
        p_entity_id,
        p_idempotency_key,
        p_old_data,
        p_new_data,
        coalesce(p_metadata, '{}'::jsonb)
    )
    returning id into audit_id;

    return audit_id;
end;
$$;

revoke all on function public.rsk_write_audit(text, text, text, uuid, jsonb, jsonb, jsonb)
    from public, anon, authenticated;

-- =====================================================================
-- 2. RPC: CREATE_ORDER_WITH_ITEMS
-- =====================================================================

create or replace function public.create_order_with_items(
    p_project_id      bigint,
    p_section_id      bigint,
    p_desired_date    date,
    p_comment         text,
    p_items           jsonb,
    p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    action_name constant text := 'create_order_with_items';
    employee_id bigint;
    employee_role text;
    current_user_id uuid;
    previous_result jsonb;
    normalized_items jsonb := '[]'::jsonb;
    item jsonb;
    item_name text;
    item_unit text;
    item_qty numeric;
    item_count integer;
    current_year integer;
    year_short text;
    number_pattern text;
    max_number bigint;
    request_number text;
    created_order public.orders%rowtype;
    result jsonb;
begin
    current_user_id := auth.uid();
    employee_id := public.rsk_current_employee_id();
    employee_role := public.rsk_current_employee_role();

    if current_user_id is null or employee_id is null then
        raise exception using errcode = '28000', message = 'Нет активного привязанного сотрудника';
    end if;
    if p_idempotency_key is null then
        raise exception using errcode = '22023', message = 'idempotency_key обязателен';
    end if;
    if employee_role not in (
        'Администратор', 'Главный инженер', 'Снабженец', 'Инженер ПТО', 'Прораб'
    ) then
        raise exception using errcode = '42501', message = 'Нет права создавать заявку на материалы';
    end if;

    -- Один actor/action/key выполняется строго один раз, включая параллельный retry.
    perform pg_advisory_xact_lock(hashtextextended(
        current_user_id::text || ':' || action_name || ':' || p_idempotency_key::text, 0
    ));

    select a.new_data -> 'result'
      into previous_result
      from public.audit_log as a
     where a.actor_user_id = current_user_id
       and a.action = action_name
       and a.idempotency_key = p_idempotency_key;
    if previous_result is not null then
        return previous_result;
    end if;

    if p_project_id is null or not exists (
        select 1 from public.projects as p where p.id = p_project_id
    ) then
        raise exception using errcode = '22023', message = 'Объект не найден';
    end if;
    if employee_role = 'Прораб' and not exists (
        select 1 from public.projects as p
        where p.id = p_project_id and p.foreman_id = employee_id
    ) then
        raise exception using errcode = '42501', message = 'Прораб может создавать заявки только по своему объекту';
    end if;
    if p_section_id is null or not exists (
        select 1 from public.sections as s
        where s.id = p_section_id and s.project_id = p_project_id
    ) then
        raise exception using errcode = '22023', message = 'Раздел не принадлежит выбранному объекту';
    end if;
    if p_desired_date is null then
        raise exception using errcode = '22023', message = 'Желаемая дата поставки обязательна';
    end if;
    if p_items is null or jsonb_typeof(p_items) <> 'array' then
        raise exception using errcode = '22023', message = 'Позиции должны быть JSON-массивом';
    end if;

    item_count := jsonb_array_length(p_items);
    if item_count < 1 or item_count > 200 then
        raise exception using errcode = '22023', message = 'В заявке должно быть от 1 до 200 позиций';
    end if;

    for item in select value from jsonb_array_elements(p_items)
    loop
        if jsonb_typeof(item) <> 'object' then
            raise exception using errcode = '22023', message = 'Каждая позиция должна быть объектом';
        end if;

        item_name := btrim(coalesce(item ->> 'name', ''));
        item_unit := btrim(coalesce(item ->> 'unit', 'шт'));
        begin
            item_qty := (item ->> 'qty')::numeric;
        exception when others then
            raise exception using errcode = '22023', message = 'Количество позиции должно быть числом';
        end;

        if item_name = '' or char_length(item_name) > 500 then
            raise exception using errcode = '22023', message = 'Название позиции обязательно и не длиннее 500 символов';
        end if;
        if item_unit = '' or char_length(item_unit) > 20 then
            raise exception using errcode = '22023', message = 'Некорректная единица измерения';
        end if;
        if item_qty::text in ('NaN', 'Infinity', '-Infinity')
           or item_qty <= 0 or item_qty > 1000000000 then
            raise exception using errcode = '22023', message = 'Количество позиции должно быть больше нуля';
        end if;

        normalized_items := normalized_items || jsonb_build_array(jsonb_build_object(
            'name', item_name,
            'unit', item_unit,
            'qty', item_qty
        ));
    end loop;

    current_year := extract(year from current_date)::integer;
    year_short := right(current_year::text, 2);

    perform pg_advisory_xact_lock(hashtextextended('rsk:order-number:' || current_year::text, 0));

    number_pattern := '^№[[:space:]]+([0-9]+)/' || year_short || '$';
    select coalesce(max((matched.parts)[1]::bigint), 0)
      into max_number
      from public.orders as o
      cross join lateral (
          select regexp_match(o.request_number, number_pattern) as parts
      ) as matched
     where matched.parts is not null
       and o.created_at >= make_date(current_year, 1, 1)
       and o.created_at < make_date(current_year + 1, 1, 1);

    request_number := format('№ %s/%s', max_number + 1, year_short);

    insert into public.orders (
        request_number,
        project_id,
        section_id,
        status,
        desired_date,
        purchase_data,
        created_by_employee_id,
        payment_source
    ) values (
        request_number,
        p_project_id,
        p_section_id,
        'new',
        p_desired_date,
        case when nullif(btrim(coalesce(p_comment, '')), '') is null
             then '{}'::jsonb
             else jsonb_build_object('comment', btrim(p_comment)) end,
        employee_id,
        'company'
    )
    returning * into created_order;

    insert into public.order_items (order_id, name, unit, qty)
    select
        created_order.id,
        rows.name,
        rows.unit,
        rows.qty
    from jsonb_to_recordset(normalized_items) as rows(name text, unit text, qty numeric);

    result := jsonb_build_object(
        'order_id', created_order.id,
        'request_number', created_order.request_number,
        'status', created_order.status,
        'items_count', item_count
    );

    perform public.rsk_write_audit(
        action_name,
        'orders',
        created_order.id::text,
        p_idempotency_key,
        null,
        jsonb_build_object(
            'result', result,
            'order', to_jsonb(created_order),
            'items', normalized_items
        ),
        jsonb_build_object('project_id', p_project_id, 'section_id', p_section_id)
    );

    return result;
end;
$$;

-- =====================================================================
-- 3. RPC: CREATE_CASH_REQUEST_WITH_ITEMS
-- =====================================================================

create or replace function public.create_cash_request_with_items(
    p_project_id      bigint,
    p_section_id      bigint,
    p_comment         text,
    p_items           jsonb,
    p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    action_name constant text := 'create_cash_request_with_items';
    employee_id bigint;
    employee_role text;
    current_user_id uuid;
    previous_result jsonb;
    normalized_items jsonb := '[]'::jsonb;
    item jsonb;
    item_name text;
    item_unit text;
    item_qty numeric;
    item_price numeric;
    item_total numeric;
    total_sum numeric := 0;
    item_count integer;
    current_year integer;
    year_short text;
    number_pattern text;
    max_number bigint;
    request_number text;
    created_request public.cash_requests%rowtype;
    result jsonb;
begin
    current_user_id := auth.uid();
    employee_id := public.rsk_current_employee_id();
    employee_role := public.rsk_current_employee_role();

    if current_user_id is null or employee_id is null then
        raise exception using errcode = '28000', message = 'Нет активного привязанного сотрудника';
    end if;
    if p_idempotency_key is null then
        raise exception using errcode = '22023', message = 'idempotency_key обязателен';
    end if;
    if employee_role not in (
        'Администратор', 'Главный инженер', 'Снабженец', 'Инженер ПТО', 'Прораб'
    ) then
        raise exception using errcode = '42501', message = 'Нет права создавать финансовую заявку';
    end if;

    perform pg_advisory_xact_lock(hashtextextended(
        current_user_id::text || ':' || action_name || ':' || p_idempotency_key::text, 0
    ));

    select a.new_data -> 'result'
      into previous_result
      from public.audit_log as a
     where a.actor_user_id = current_user_id
       and a.action = action_name
       and a.idempotency_key = p_idempotency_key;
    if previous_result is not null then
        return previous_result;
    end if;

    if p_project_id is null or not exists (
        select 1 from public.projects as p where p.id = p_project_id
    ) then
        raise exception using errcode = '22023', message = 'Объект не найден';
    end if;
    if employee_role = 'Прораб' and not exists (
        select 1 from public.projects as p
        where p.id = p_project_id and p.foreman_id = employee_id
    ) then
        raise exception using errcode = '42501', message = 'Прораб может создавать заявки только по своему объекту';
    end if;
    if p_section_id is null or not exists (
        select 1 from public.sections as s
        where s.id = p_section_id and s.project_id = p_project_id
    ) then
        raise exception using errcode = '22023', message = 'Раздел не принадлежит выбранному объекту';
    end if;
    if p_items is null or jsonb_typeof(p_items) <> 'array' then
        raise exception using errcode = '22023', message = 'Позиции должны быть JSON-массивом';
    end if;

    item_count := jsonb_array_length(p_items);
    if item_count < 1 or item_count > 200 then
        raise exception using errcode = '22023', message = 'В заявке должно быть от 1 до 200 позиций';
    end if;

    for item in select value from jsonb_array_elements(p_items)
    loop
        if jsonb_typeof(item) <> 'object' then
            raise exception using errcode = '22023', message = 'Каждая позиция должна быть объектом';
        end if;

        item_name := btrim(coalesce(item ->> 'name', ''));
        item_unit := btrim(coalesce(item ->> 'unit', 'м²'));
        begin
            item_qty := (item ->> 'qty')::numeric;
            item_price := (item ->> 'unit_price')::numeric;
        exception when others then
            raise exception using errcode = '22023', message = 'Количество и цена позиции должны быть числами';
        end;

        if item_name = '' or char_length(item_name) > 500 then
            raise exception using errcode = '22023', message = 'Название позиции обязательно и не длиннее 500 символов';
        end if;
        if item_unit = '' or char_length(item_unit) > 20 then
            raise exception using errcode = '22023', message = 'Некорректная единица измерения';
        end if;
        if item_qty::text in ('NaN', 'Infinity', '-Infinity')
           or item_qty <= 0 or item_qty > 1000000000 then
            raise exception using errcode = '22023', message = 'Количество позиции должно быть больше нуля';
        end if;
        if item_price::text in ('NaN', 'Infinity', '-Infinity')
           or item_price <= 0 or item_price > 1000000000000 then
            raise exception using errcode = '22023', message = 'Цена позиции должна быть больше нуля';
        end if;

        item_qty := round(item_qty, 6);
        item_price := round(item_price, 2);
        item_total := round(item_qty * item_price, 2);
        total_sum := round(total_sum + item_total, 2);

        if item_total <= 0 or total_sum > 1000000000000000 then
            raise exception using errcode = '22023', message = 'Некорректная итоговая сумма заявки';
        end if;

        normalized_items := normalized_items || jsonb_build_array(jsonb_build_object(
            'name', item_name,
            'unit', item_unit,
            'qty', item_qty,
            'unit_price', item_price,
            'total_price', item_total
        ));
    end loop;

    current_year := extract(year from current_date)::integer;
    year_short := right(current_year::text, 2);

    perform pg_advisory_xact_lock(hashtextextended('rsk:cash-request-number:' || current_year::text, 0));

    number_pattern := '^Ф-([0-9]+)/' || year_short || '$';
    select coalesce(max((matched.parts)[1]::bigint), 0)
      into max_number
      from public.cash_requests as r
      cross join lateral (
          select regexp_match(r.request_number, number_pattern) as parts
      ) as matched
     where matched.parts is not null
       and r.created_at >= make_date(current_year, 1, 1)
       and r.created_at < make_date(current_year + 1, 1, 1);

    request_number := format('Ф-%s/%s', max_number + 1, year_short);

    insert into public.cash_requests (
        request_number,
        project_id,
        section_id,
        employee_id,
        total_sum,
        comment,
        status
    ) values (
        request_number,
        p_project_id,
        p_section_id,
        employee_id,
        total_sum,
        nullif(btrim(coalesce(p_comment, '')), ''),
        'pending'
    )
    returning * into created_request;

    insert into public.cash_request_items (
        request_id, name, unit, qty, unit_price, total_price
    )
    select
        created_request.id,
        rows.name,
        rows.unit,
        rows.qty,
        rows.unit_price,
        rows.total_price
    from jsonb_to_recordset(normalized_items) as rows(
        name text, unit text, qty numeric, unit_price numeric, total_price numeric
    );

    result := jsonb_build_object(
        'request_id', created_request.id,
        'request_number', created_request.request_number,
        'status', created_request.status,
        'total_sum', created_request.total_sum,
        'items_count', item_count
    );

    perform public.rsk_write_audit(
        action_name,
        'cash_requests',
        created_request.id::text,
        p_idempotency_key,
        null,
        jsonb_build_object(
            'result', result,
            'request', to_jsonb(created_request),
            'items', normalized_items
        ),
        jsonb_build_object('project_id', p_project_id, 'section_id', p_section_id)
    );

    return result;
end;
$$;

-- =====================================================================
-- 4. RPC: ISSUE_CASH_REQUEST
-- =====================================================================

create or replace function public.issue_cash_request(
    p_request_id      bigint,
    p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    action_name constant text := 'issue_cash_request';
    employee_id bigint;
    employee_role text;
    current_user_id uuid;
    previous_result jsonb;
    request_before public.cash_requests%rowtype;
    request_after public.cash_requests%rowtype;
    recipient_operation public.cash_operations%rowtype;
    financier_operation public.cash_operations%rowtype;
    recipient_name text;
    result jsonb;
begin
    current_user_id := auth.uid();
    employee_id := public.rsk_current_employee_id();
    employee_role := public.rsk_current_employee_role();

    if current_user_id is null or employee_id is null then
        raise exception using errcode = '28000', message = 'Нет активного привязанного сотрудника';
    end if;
    if p_idempotency_key is null then
        raise exception using errcode = '22023', message = 'idempotency_key обязателен';
    end if;
    if employee_role not in ('Администратор', 'Главный инженер', 'Финансист') then
        raise exception using errcode = '42501', message = 'Нет права выдавать деньги по заявке';
    end if;

    perform pg_advisory_xact_lock(hashtextextended(
        current_user_id::text || ':' || action_name || ':' || p_idempotency_key::text, 0
    ));

    select a.new_data -> 'result'
      into previous_result
      from public.audit_log as a
     where a.actor_user_id = current_user_id
       and a.action = action_name
       and a.idempotency_key = p_idempotency_key;
    if previous_result is not null then
        return previous_result;
    end if;

    select r.*
      into request_before
      from public.cash_requests as r
     where r.id = p_request_id
     for update;

    if not found then
        raise exception using errcode = 'P0002', message = 'Финансовая заявка не найдена';
    end if;
    if request_before.status <> 'approved' then
        raise exception using errcode = 'P0001', message = 'Заявка должна быть в статусе "Одобрено"';
    end if;
    if request_before.total_sum is null or request_before.total_sum <= 0 then
        raise exception using errcode = '22023', message = 'Сумма заявки должна быть больше нуля';
    end if;

    select e.name
      into recipient_name
      from public.employees as e
     where e.id = request_before.employee_id
       and coalesce(e.status, 'active') = 'active';
    if not found then
        raise exception using errcode = 'P0001', message = 'Получатель заявки неактивен или не найден';
    end if;

    insert into public.cash_operations (
        employee_id,
        operation_type,
        amount,
        description,
        source,
        operation_date,
        created_by
    ) values (
        request_before.employee_id,
        'issue',
        request_before.total_sum,
        format('Заявка %s — выдача подотчёта', request_before.request_number),
        'cash_request_issue',
        current_date,
        current_user_id
    )
    returning * into recipient_operation;

    if employee_role = 'Финансист' then
        insert into public.cash_operations (
            employee_id,
            operation_type,
            amount,
            description,
            source,
            operation_date,
            created_by
        ) values (
            employee_id,
            'return',
            request_before.total_sum,
            format('Выдача по заявке %s — %s', request_before.request_number, recipient_name),
            'cash_request_debit',
            current_date,
            current_user_id
        )
        returning * into financier_operation;
    end if;

    update public.cash_requests
       set status = 'issued',
           issued_operation_id = recipient_operation.id
     where id = request_before.id
    returning * into request_after;

    result := jsonb_build_object(
        'request_id', request_after.id,
        'request_number', request_after.request_number,
        'status', request_after.status,
        'amount', request_after.total_sum,
        'recipient_operation_id', recipient_operation.id,
        'financier_operation_id', case when employee_role = 'Финансист'
                                       then financier_operation.id else null end
    );

    perform public.rsk_write_audit(
        action_name,
        'cash_requests',
        request_after.id::text,
        p_idempotency_key,
        to_jsonb(request_before),
        jsonb_build_object(
            'result', result,
            'request', to_jsonb(request_after),
            'recipient_operation', to_jsonb(recipient_operation),
            'financier_operation', case when employee_role = 'Финансист'
                                        then to_jsonb(financier_operation) else null end
        ),
        jsonb_build_object('issued_by_role', employee_role)
    );

    return result;
end;
$$;

-- =====================================================================
-- 5. RPC: SAVE_OWN_DELIVERY_EXPENSE
-- =====================================================================

create or replace function public.save_own_delivery_expense(
    p_order_id        bigint,
    p_enabled         boolean,
    p_amount          numeric,
    p_charge          text,
    p_employee_id     bigint,
    p_vat_rate        numeric,
    p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    action_name constant text := 'save_own_delivery_expense';
    employee_id bigint;
    employee_role text;
    current_user_id uuid;
    previous_result jsonb;
    order_row public.orders%rowtype;
    old_operation public.cash_operations%rowtype;
    new_operation public.cash_operations%rowtype;
    has_old boolean := false;
    payer_id bigint;
    normalized_rate numeric;
    normalized_amount numeric;
    vat_amount numeric;
    result jsonb;
begin
    current_user_id := auth.uid();
    employee_id := public.rsk_current_employee_id();
    employee_role := public.rsk_current_employee_role();

    if current_user_id is null or employee_id is null then
        raise exception using errcode = '28000', message = 'Нет активного привязанного сотрудника';
    end if;
    if p_idempotency_key is null then
        raise exception using errcode = '22023', message = 'idempotency_key обязателен';
    end if;
    if employee_role not in ('Администратор', 'Снабженец') then
        raise exception using errcode = '42501', message = 'Нет права сохранять расход своей доставки';
    end if;

    perform pg_advisory_xact_lock(hashtextextended(
        current_user_id::text || ':' || action_name || ':' || p_idempotency_key::text, 0
    ));

    select a.new_data -> 'result'
      into previous_result
      from public.audit_log as a
     where a.actor_user_id = current_user_id
       and a.action = action_name
       and a.idempotency_key = p_idempotency_key;
    if previous_result is not null then
        return previous_result;
    end if;

    select o.*
      into order_row
      from public.orders as o
     where o.id = p_order_id
     for update;
    if not found then
        raise exception using errcode = 'P0002', message = 'Заявка на материалы не найдена';
    end if;

    if p_charge not in ('snagach', 'employee', 'firm') then
        raise exception using errcode = '22023', message = 'Некорректный способ оплаты своей доставки';
    end if;

    select operation.*
      into old_operation
      from public.cash_operations as operation
     where operation.order_id = p_order_id
       and operation.source = 'own_delivery'
     for update;
    has_old := found;

    -- Платит фирма, доставка отключена или сумма очищена: расхода подотчёта нет.
    if not coalesce(p_enabled, false)
       or p_charge = 'firm'
       or coalesce(p_amount, 0) <= 0 then
        if has_old then
            delete from public.cash_operations where id = old_operation.id;
        end if;

        result := jsonb_build_object(
            'order_id', p_order_id,
            'operation_id', null,
            'action', case when has_old then 'deleted' else 'unchanged' end,
            'amount', 0
        );

        perform public.rsk_write_audit(
            action_name,
            'cash_operations',
            case when has_old then old_operation.id::text else p_order_id::text end,
            p_idempotency_key,
            case when has_old then to_jsonb(old_operation) else null end,
            jsonb_build_object('result', result, 'operation', null),
            jsonb_build_object('order_id', p_order_id, 'charge', p_charge)
        );
        return result;
    end if;

    normalized_amount := round(p_amount, 2);
    if normalized_amount::text in ('NaN', 'Infinity', '-Infinity')
       or normalized_amount <= 0 or normalized_amount > 1000000000000 then
        raise exception using errcode = '22023', message = 'Сумма доставки должна быть больше нуля';
    end if;

    normalized_rate := least(greatest(coalesce(p_vat_rate, 0), 0), 100);
    if normalized_rate::text in ('NaN', 'Infinity', '-Infinity') then
        normalized_rate := 0;
    end if;
    vat_amount := case when normalized_rate > 0
                       then round(normalized_amount * normalized_rate / (100 + normalized_rate), 2)
                       else 0 end;

    if p_charge = 'employee' then
        payer_id := p_employee_id;
        if payer_id is null or not exists (
            select 1 from public.employees as e
            where e.id = payer_id and coalesce(e.status, 'active') = 'active'
        ) then
            raise exception using errcode = '22023', message = 'Выбранный сотрудник неактивен или не найден';
        end if;
    else
        payer_id := employee_id;
    end if;

    if has_old then
        update public.cash_operations
           set employee_id = payer_id,
               operation_type = 'expense',
               amount = normalized_amount,
               category = 'delivery',
               project_id = order_row.project_id,
               section_id = order_row.section_id,
               order_id = order_row.id,
               items = jsonb_build_array(jsonb_build_object(
                   'name', 'Доставка компании',
                   'unit', 'усл.',
                   'qty', 1,
                   'price', normalized_amount,
                   'sum', normalized_amount
               )),
               vat_rate = normalized_rate,
               vat_amount = vat_amount,
               source = 'own_delivery',
               description = format('Своя доставка по заявке %s', order_row.request_number),
               operation_date = current_date,
               created_by = current_user_id
         where id = old_operation.id
        returning * into new_operation;
    else
        insert into public.cash_operations (
            employee_id,
            operation_type,
            amount,
            category,
            project_id,
            section_id,
            order_id,
            items,
            vat_rate,
            vat_amount,
            source,
            description,
            operation_date,
            created_by
        ) values (
            payer_id,
            'expense',
            normalized_amount,
            'delivery',
            order_row.project_id,
            order_row.section_id,
            order_row.id,
            jsonb_build_array(jsonb_build_object(
                'name', 'Доставка компании',
                'unit', 'усл.',
                'qty', 1,
                'price', normalized_amount,
                'sum', normalized_amount
            )),
            normalized_rate,
            vat_amount,
            'own_delivery',
            format('Своя доставка по заявке %s', order_row.request_number),
            current_date,
            current_user_id
        )
        returning * into new_operation;
    end if;

    result := jsonb_build_object(
        'order_id', p_order_id,
        'operation_id', new_operation.id,
        'action', case when has_old then 'updated' else 'created' end,
        'employee_id', new_operation.employee_id,
        'amount', new_operation.amount,
        'vat_amount', new_operation.vat_amount
    );

    perform public.rsk_write_audit(
        action_name,
        'cash_operations',
        new_operation.id::text,
        p_idempotency_key,
        case when has_old then to_jsonb(old_operation) else null end,
        jsonb_build_object('result', result, 'operation', to_jsonb(new_operation)),
        jsonb_build_object('order_id', p_order_id, 'charge', p_charge)
    );

    return result;
end;
$$;

-- =====================================================================
-- 6. ПРАВА НА RPC
-- =====================================================================

revoke all on function public.create_order_with_items(bigint, bigint, date, text, jsonb, uuid)
    from public, anon;
revoke all on function public.create_cash_request_with_items(bigint, bigint, text, jsonb, uuid)
    from public, anon;
revoke all on function public.issue_cash_request(bigint, uuid)
    from public, anon;
revoke all on function public.save_own_delivery_expense(bigint, boolean, numeric, text, bigint, numeric, uuid)
    from public, anon;

grant execute on function public.create_order_with_items(bigint, bigint, date, text, jsonb, uuid)
    to authenticated;
grant execute on function public.create_cash_request_with_items(bigint, bigint, text, jsonb, uuid)
    to authenticated;
grant execute on function public.issue_cash_request(bigint, uuid)
    to authenticated;
grant execute on function public.save_own_delivery_expense(bigint, boolean, numeric, text, bigint, numeric, uuid)
    to authenticated;

-- =====================================================================
-- 7. ЗАКРЫТИЕ ВРЕМЕННЫХ ПРЯМЫХ ЗАПИСЕЙ
-- =====================================================================

-- Финансист теперь выдаёт только через issue_cash_request().
drop policy if exists rsk_cash_operations_insert_financier_transition
    on public.cash_operations;

-- Снабженец теперь сохраняет свою доставку только через
-- save_own_delivery_expense().
drop policy if exists rsk_cash_operations_insert_own_delivery
    on public.cash_operations;
drop policy if exists rsk_cash_operations_update_own_delivery
    on public.cash_operations;
drop policy if exists rsk_cash_operations_delete_own_delivery
    on public.cash_operations;

-- Новая финансовая заявка создаётся только create_cash_request_with_items().
drop policy if exists rsk_cash_requests_insert_own on public.cash_requests;
revoke insert on table public.cash_requests from authenticated;

-- Заголовок заявки материалов создаётся только create_order_with_items().
-- order_items пока остаётся доступен текущему потоку счёта/доставки.
revoke insert on table public.orders from anon, authenticated;

commit;

notify pgrst, 'reload schema';

-- =====================================================================
-- 8. САМОПРОВЕРКА
-- =====================================================================

-- Четыре строки, exists = true, authenticated_execute = true,
-- anon_execute = false.
select
    checks.function_name,
    to_regprocedure(checks.signature) is not null as exists,
    has_function_privilege('authenticated', checks.signature, 'EXECUTE') as authenticated_execute,
    has_function_privilege('anon', checks.signature, 'EXECUTE') as anon_execute
from (values
    ('create_order_with_items',
     'public.create_order_with_items(bigint,bigint,date,text,jsonb,uuid)'),
    ('create_cash_request_with_items',
     'public.create_cash_request_with_items(bigint,bigint,text,jsonb,uuid)'),
    ('issue_cash_request',
     'public.issue_cash_request(bigint,uuid)'),
    ('save_own_delivery_expense',
     'public.save_own_delivery_expense(bigint,boolean,numeric,text,bigint,numeric,uuid)')
) as checks(function_name, signature)
order by checks.function_name;

-- RLS enabled/forced; authenticated может только SELECT.
select
    c.relname as table_name,
    c.relrowsecurity as rls_enabled,
    c.relforcerowsecurity as rls_forced,
    has_table_privilege('authenticated', 'public.audit_log', 'SELECT') as authenticated_select,
    has_table_privilege('authenticated', 'public.audit_log', 'INSERT') as authenticated_insert,
    has_table_privilege('authenticated', 'public.audit_log', 'UPDATE') as authenticated_update,
    has_table_privilege('authenticated', 'public.audit_log', 'DELETE') as authenticated_delete
from pg_class as c
join pg_namespace as n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relname = 'audit_log';

-- Все временные политики должны отсутствовать.
select
    expected.policy_name,
    case when policies.policyname is null then 'removed' else 'STILL PRESENT' end as status
from (values
    ('rsk_cash_operations_insert_financier_transition'),
    ('rsk_cash_operations_insert_own_delivery'),
    ('rsk_cash_operations_update_own_delivery'),
    ('rsk_cash_operations_delete_own_delivery'),
    ('rsk_cash_requests_insert_own')
) as expected(policy_name)
left join pg_policies as policies
  on policies.schemaname = 'public'
 and policies.policyname = expected.policy_name
order by expected.policy_name;

-- Оба значения должны быть false: создание родителя — только RPC.
select
    has_table_privilege('authenticated', 'public.orders', 'INSERT') as direct_order_insert,
    has_table_privilege('authenticated', 'public.cash_requests', 'INSERT') as direct_cash_request_insert;

-- Оба индекса должны существовать.
select
    indexname,
    indexdef
from pg_indexes
where schemaname = 'public'
  and indexname in (
      'audit_log_command_once',
      'cash_operations_one_own_delivery_per_order'
  )
order by indexname;
