-- =====================================================================
-- FREEDOM — СМЕТЫ (конструктор смет для ПТО)
-- Версия: 2.10.0
-- =====================================================================
-- Что делает эта миграция:
--   1. справочники сметы — работы, материалы, их разделы и единицы
--      измерения, нормы расхода материалов на работу (работа → материалы);
--   2. клиенты (заказчики) и реквизиты своей компании — для документов;
--   3. сами сметы: разделы → позиции → материалы позиции + лимитированные
--      расходы и ПДВ;
--   4. RLS: читать и править может только тройка ролей, которой открыт
--      модуль (Администратор, Главный инженер, Инженер ПТО) — то же право
--      manage_estimate, что и у блока «📊 Смета объекта»;
--   5. команды базы: номер сметы и транзакционное сохранение сметы целиком.
--
-- ПОЧЕМУ НОМЕР И СОХРАНЕНИЕ — В БАЗЕ. Смета сохраняется не одной строкой, а
-- агрегатом (разделы, позиции, материалы, лимиты). Если сохранять это из
-- браузера по частям, обрыв сети посреди операции оставит смету «половинкой»:
-- разделы без позиций. Поэтому запись идёт одной командой базы в транзакции,
-- а номер выдаётся под блокировкой — иначе двое, нажавшие «Создать смету»
-- одновременно, получат одинаковый номер (колонка number уникальна).
--
-- ЗАВИСИМОСТИ: public.rsk_current_employee_role() и
-- public.rsk_current_employee_id() из database/migrate-v2.7-rls-finance.sql —
-- если она не применена, сначала выполните её. Первая решает, кому открыт
-- раздел (Администратор, Главный инженер, Инженер ПТО), вторая записывается
-- автором сметы; без второй смета не сохранится вообще.
--
-- Файл можно запускать повторно: таблицы создаются через if not exists,
-- политики сначала удаляются, функции заменяются.
-- =====================================================================

begin;

-- =====================================================================
-- 1. СПРАВОЧНИК ЕДИНИЦ ИЗМЕРЕНИЯ
-- =====================================================================

create table if not exists public.estimate_units (
    id          bigint generated by default as identity primary key,
    name        text        not null unique,     -- 'м²'
    full_name   text,                            -- 'метр квадратний'
    order_index integer     not null default 0,
    created_at  timestamptz not null default now()
);


-- =====================================================================
-- 2. РАЗДЕЛЫ СПРАВОЧНИКОВ (дерево: «Покрівля» → «Покрівля скатна»)
-- =====================================================================
-- Два одинаковых по структуре дерева: разделы работ и разделы материалов.
-- Отдельные таблицы, а не одна с признаком вида: так ссылки из работ и
-- материалов остаются простыми (section_id → одна понятная таблица).

create table if not exists public.estimate_work_sections (
    id           bigint generated by default as identity primary key,
    name         text        not null,
    parent_id    bigint      references public.estimate_work_sections(id) on delete cascade,
    order_index  integer     not null default 0,
    created_at   timestamptz not null default now()
);

create table if not exists public.estimate_material_sections (
    id           bigint generated by default as identity primary key,
    name         text        not null,
    parent_id    bigint      references public.estimate_material_sections(id) on delete cascade,
    order_index  integer     not null default 0,
    created_at   timestamptz not null default now()
);

-- =====================================================================
-- 3. СПРАВОЧНИК РАБОТ
-- =====================================================================
-- price_worker  — «наряд»: сколько получает исполнитель за единицу;
-- price_client  — «кошторис»: сколько платит заказчик за единицу.
-- Разница и есть прибыль по работе, поэтому обе цены обязательны.

create table if not exists public.estimate_works (
    id           bigint generated by default as identity primary key,
    name         text        not null,
    unit         text        not null default 'шт',
    price_worker numeric     not null default 0,
    price_client numeric     not null default 0,
    description  text,
    section_id   bigint      references public.estimate_work_sections(id) on delete set null,
    created_at   timestamptz not null default now()
);

-- =====================================================================
-- 4. СПРАВОЧНИК МАТЕРИАЛОВ
-- =====================================================================
-- price_purchase        — «наряд»: цена закупки (себестоимость);
-- price_client          — «кошторис»: цена заказчику;
-- is_customer_supplied  — давальческий: привозит заказчик, в суммы не входит.

create table if not exists public.estimate_materials (
    id                   bigint generated by default as identity primary key,
    name                 text        not null,
    unit                 text        not null default 'шт',
    price_purchase       numeric     not null default 0,
    price_client         numeric     not null default 0,
    is_customer_supplied boolean     not null default false,
    section_id           bigint      references public.estimate_material_sections(id) on delete set null,
    created_at           timestamptz not null default now()
);

-- =====================================================================
-- 5. НОРМЫ РАСХОДА: СКОЛЬКО МАТЕРИАЛА НУЖНО НА ЕДИНИЦУ РАБОТЫ
-- =====================================================================
-- consumption — расход материала на 1 единицу работы (например, 0.02 т
-- цемента на 1 м² стяжки). По этим нормам смета сама подставляет материалы
-- в позицию и пересчитывает их количество от объёма работы.

create table if not exists public.estimate_work_materials (
    id          bigint generated by default as identity primary key,
    work_id     bigint  not null references public.estimate_works(id) on delete cascade,
    material_id bigint  not null references public.estimate_materials(id) on delete cascade,
    consumption numeric not null default 0,
    created_at  timestamptz not null default now(),
    unique (work_id, material_id)
);

-- =====================================================================
-- 6. КЛИЕНТЫ (ЗАКАЗЧИКИ) И РЕКВИЗИТЫ СВОЕЙ КОМПАНИИ
-- =====================================================================
-- Клиенты — отдельный справочник, а не поле «объект»: у одного заказчика
-- бывает несколько объектов, и в документах нужны его реквизиты.
-- Реквизиты компании — ровно одна строка (id = 1): их печатают шапкой
-- кошториса и наряда, поэтому в смете они не дублируются.

create table if not exists public.estimate_clients (
    id         bigint generated by default as identity primary key,
    name       text        not null,
    phone      text,
    email      text,
    address    text,
    notes      text,
    created_at timestamptz not null default now()
);

create table if not exists public.estimate_company (
    id            bigint primary key default 1 check (id = 1),
    company_name  text,
    phone         text,
    email         text,
    website       text,
    address       text,
    default_notes text,
    updated_at    timestamptz not null default now()
);

-- =====================================================================
-- 7. СМЕТА: РАЗДЕЛЫ → ПОЗИЦИИ → МАТЕРИАЛЫ ПОЗИЦИИ + ЛИМИТЫ
-- =====================================================================
-- projects (необязательно) — объект стройки: смета привязывается к нему,
-- чтобы план из сметы можно было перенести в разделы объекта (план-факт).
-- Позиция хранит СВОИ цены (price_worker/price_client), а не только ссылку
-- на справочник: справочник меняется со временем, а смета заказчику — это
-- документ, её суммы не должны «поехать» от правки прайса.

create table if not exists public.estimates (
    id                    bigint generated by default as identity primary key,
    number                text        not null unique,      -- '00001/2026'
    number_year           integer     not null,
    number_seq            integer     not null,
    title                 text        not null,
    object_name           text,
    project_id            bigint      references public.projects(id) on delete set null,
    client_id             bigint      references public.estimate_clients(id) on delete set null,
    notes                 text,
    vat_percent           numeric     not null default 0,
    vat_base              text        not null default 'both',   -- works | materials | both
    status                text        not null default 'draft',  -- draft | approved | archived
    created_by_employee_id bigint     references public.employees(id) on delete set null,
    created_at            timestamptz not null default now(),
    updated_at            timestamptz not null default now(),
    -- Итоги сметы. Считает их save_estimate() один раз при сохранении: списку
    -- смет нужны суммы, а тянуть ради этого все разделы, позиции и материалы
    -- каждой сметы — десятки лишних запросов на один экран.
    --   total_client    — сумма к оплате заказчиком (работы + материалы +
    --                     лимиты + ПДВ);
    --   total_materials — материалы по кошторисным ценам (без давальческих);
    --   total_naryad    — наша себестоимость (работы + закупка материалов);
    --   items_count     — сколько позиций в смете.
    total_client          numeric     not null default 0,
    total_materials       numeric     not null default 0,
    total_naryad          numeric     not null default 0,
    items_count           integer     not null default 0
);

create table if not exists public.estimate_sections (
    id          bigint generated by default as identity primary key,
    estimate_id bigint  not null references public.estimates(id) on delete cascade,
    name        text    not null,
    order_index integer not null default 0
);

create table if not exists public.estimate_items (
    id           bigint generated by default as identity primary key,
    section_id   bigint  not null references public.estimate_sections(id) on delete cascade,
    work_id      bigint  references public.estimate_works(id) on delete set null,
    name         text    not null,
    unit         text    not null default 'шт',
    quantity     numeric not null default 0,
    price_worker numeric not null default 0,
    price_client numeric not null default 0,
    order_index  integer not null default 0
);

create table if not exists public.estimate_item_materials (
    id                   bigint generated by default as identity primary key,
    item_id              bigint  not null references public.estimate_items(id) on delete cascade,
    material_id          bigint  references public.estimate_materials(id) on delete set null,
    name                 text    not null,
    unit                 text    not null default 'шт',
    quantity             numeric not null default 0,
    price_purchase       numeric not null default 0,
    price_client         numeric not null default 0,
    consumption          numeric,
    is_customer_supplied boolean not null default false,
    order_index          integer not null default 0
);

create table if not exists public.estimate_limits (
    id          bigint generated by default as identity primary key,
    estimate_id bigint  not null references public.estimates(id) on delete cascade,
    name        text    not null,
    percent     numeric not null default 0,
    base        text    not null default 'both',   -- works | materials | both
    order_index integer not null default 0
);

-- Журнал команд сметы: защита от двойного нажатия «Сохранить». Ключ запроса
-- приходит из браузера (db.newCommandKey), повтор возвращает прежний
-- результат вместо второй сметы.
create table if not exists public.estimate_command_log (
    command_key uuid primary key,
    estimate_id bigint,
    created_at  timestamptz not null default now()
);

-- =====================================================================
-- 8. ИНДЕКСЫ
-- =====================================================================
-- Смета читается целиком (разделы → позиции → материалы): это десятки строк,
-- но по ним идут соединения, поэтому внешние ключи индексируем — иначе
-- Postgres сканирует таблицы целиком на каждый уровень вложенности.
-- Отдельные индексы — под списки: сметы объекта, поиск по названию
-- справочника, нормы конкретной работы.

create index if not exists estimate_works_section_idx
    on public.estimate_works (section_id);
create index if not exists estimate_materials_section_idx
    on public.estimate_materials (section_id);
create index if not exists estimate_work_materials_work_idx
    on public.estimate_work_materials (work_id);
create index if not exists estimate_work_materials_material_idx
    on public.estimate_work_materials (material_id);
create index if not exists estimates_project_idx
    on public.estimates (project_id);
create index if not exists estimates_client_idx
    on public.estimates (client_id);
create index if not exists estimates_year_seq_idx
    on public.estimates (number_year, number_seq desc);
create index if not exists estimate_sections_estimate_idx
    on public.estimate_sections (estimate_id);
create index if not exists estimate_items_section_idx
    on public.estimate_items (section_id);
create index if not exists estimate_items_work_idx
    on public.estimate_items (work_id);
create index if not exists estimate_item_materials_item_idx
    on public.estimate_item_materials (item_id);
create index if not exists estimate_limits_estimate_idx
    on public.estimate_limits (estimate_id);

-- =====================================================================
-- 9. RLS: СМЕТУ ВИДИТ ТОЛЬКО ТРОЙКА РОЛЕЙ ПТО
-- =====================================================================
-- Те же роли, что у права manage_estimate в js/permissions.js:
-- Администратор, Главный инженер, Инженер ПТО. Смета — рабочий документ ПТО
-- и коммерческая тайна (в ней цены «наряд» и «кошторис», то есть прибыль),
-- поэтому директору и прорабу её не показывают: RLS закрывает данные даже
-- если кто-то откроет консоль браузера.

create or replace function public.rsk_is_estimate_editor()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
    select coalesce(public.rsk_current_employee_role(), '') in
        ('Администратор', 'Главный инженер', 'Инженер ПТО')
$$;

revoke all on function public.rsk_is_estimate_editor() from public;
grant execute on function public.rsk_is_estimate_editor() to authenticated;

-- Справочники: правят только редакторы смет.
do $$
declare
    tbl text;
begin
    foreach tbl in array array[
        'estimate_units', 'estimate_work_sections', 'estimate_material_sections',
        'estimate_works', 'estimate_materials', 'estimate_work_materials',
        'estimate_clients', 'estimate_company'
    ] loop
        execute format('revoke all on table public.%I from anon', tbl);
        execute format('revoke all on table public.%I from authenticated', tbl);
        execute format('grant select, insert, update, delete on table public.%I to authenticated', tbl);
        execute format('alter table public.%I enable row level security', tbl);
        execute format('drop policy if exists %I on public.%I', tbl || '_estimate_editor', tbl);
        execute format(
            'create policy %I on public.%I for all to authenticated using (public.rsk_is_estimate_editor()) with check (public.rsk_is_estimate_editor())',
            tbl || '_estimate_editor', tbl
        );
    end loop;
end $$;

-- Дочерние таблицы сметы: мало быть редактором — нужна ещё смета-владелец
-- (проверка поднимается по ссылкам до public.estimates). Так строка чужой
-- сметы недоступна, даже если её id подставить вручную.
do $$
declare
    spec record;
begin
    for spec in
        select * from (values
            ('estimate_sections', 'exists (select 1 from public.estimates e where e.id = estimate_id)'),
            ('estimate_limits',   'exists (select 1 from public.estimates e where e.id = estimate_id)'),
            ('estimate_items',    'exists (select 1 from public.estimate_sections s join public.estimates e on e.id = s.estimate_id where s.id = section_id)'),
            ('estimate_item_materials', 'exists (select 1 from public.estimate_items i join public.estimate_sections s on s.id = i.section_id join public.estimates e on e.id = s.estimate_id where i.id = item_id)')
        ) as t(tbl, parent_check)
    loop
        execute format('revoke all on table public.%I from anon', spec.tbl);
        execute format('revoke all on table public.%I from authenticated', spec.tbl);
        -- Только чтение: строки сметы пишет save_estimate() — иначе смету можно
        -- собрать «по кускам» и оставить её без разделов или без позиций.
        execute format('grant select on table public.%I to authenticated', spec.tbl);
        execute format('alter table public.%I enable row level security', spec.tbl);
        execute format('drop policy if exists %I on public.%I', spec.tbl || '_estimate_editor', spec.tbl);
        execute format(
            'create policy %I on public.%I for all to authenticated using (public.rsk_is_estimate_editor() and %s) with check (public.rsk_is_estimate_editor() and %s)',
            spec.tbl || '_estimate_editor', spec.tbl, spec.parent_check, spec.parent_check
        );
    end loop;

    -- Сами сметы: чтение открыто редакторам, запись — только командами базы.
    revoke all on table public.estimates from anon;
    revoke all on table public.estimates from authenticated;
    grant select on table public.estimates to authenticated;
    alter table public.estimates enable row level security;
    drop policy if exists estimates_estimate_editor on public.estimates;
    create policy estimates_estimate_editor on public.estimates
        for all to authenticated
        using (public.rsk_is_estimate_editor())
        with check (public.rsk_is_estimate_editor());

    -- Журнал команд: только чтение редакторами; пишет его команда базы.
    revoke all on table public.estimate_command_log from anon;
    revoke all on table public.estimate_command_log from authenticated;
    grant select on table public.estimate_command_log to authenticated;
    alter table public.estimate_command_log enable row level security;
    drop policy if exists estimate_command_log_read on public.estimate_command_log;
    create policy estimate_command_log_read on public.estimate_command_log
        for select to authenticated
        using (public.rsk_is_estimate_editor());
end $$;

-- Последовательности identity: без права на них INSERT через PostgREST
-- упадёт с «permission denied for sequence».
do $$
declare
    tbl text;
    seq text;
begin
    foreach tbl in array array[
        'estimate_units', 'estimate_work_sections', 'estimate_material_sections',
        'estimate_works', 'estimate_materials', 'estimate_work_materials',
        'estimate_clients', 'estimates', 'estimate_sections', 'estimate_items',
        'estimate_item_materials', 'estimate_limits'
    ] loop
        seq := pg_get_serial_sequence('public.' || tbl, 'id');
        if seq is not null then
            execute format('grant usage, select on sequence %s to authenticated', seq);
        end if;
    end loop;
end $$;

-- =====================================================================
-- 10. КОМАНДЫ БАЗЫ: НОМЕР СМЕТЫ И СОХРАНЕНИЕ СМЕТЫ ЦЕЛИКОМ
-- =====================================================================

-- Номер сметы: «00001/2026» — пять цифр и год, как в бумажных сметах.
-- Блокировка (pg_advisory_xact_lock) держится до конца транзакции, поэтому
-- два одновременных создания не получат один и тот же номер.
create or replace function public.estimate_next_number()
returns table (number text, number_year integer, number_seq integer)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    v_year integer := extract(year from now())::integer;
    v_seq  integer;
begin
    if not public.rsk_is_estimate_editor() then
        raise exception 'Сметы доступны Администратору, Главному инженеру и Инженеру ПТО';
    end if;

    perform pg_advisory_xact_lock(hashtext('freedom.estimates.number'));

    select coalesce(max(e.number_seq), 0) + 1
      into v_seq
      from public.estimates e
     where e.number_year = v_year;

    return query select lpad(v_seq::text, 5, '0') || '/' || v_year::text, v_year, v_seq;
end $$;

revoke all on function public.estimate_next_number() from public;
grant execute on function public.estimate_next_number() to authenticated;

-- Сохранение сметы целиком: шапка + разделы + позиции + материалы позиций +
-- лимиты. Одна транзакция — либо смета сохранена полностью, либо не изменена.
-- Возвращает строку сметы (jsonb): по ней браузер узнаёт присвоенный номер.
--
-- p_estimate_id = null → новая смета; иначе — обновление существующей
-- (номер и год не меняются: смета уже у заказчика).
-- p_command_key — ключ идемпотентности (db.newCommandKey() в браузере):
-- повторная доставка того же запроса не создаст вторую смету.
create or replace function public.save_estimate(
    p_payload      jsonb,
    p_estimate_id  bigint default null,
    p_command_key  uuid   default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    v_id        bigint;
    v_existing  bigint;
    v_number    text;
    v_year      integer;
    v_seq       integer;
    v_section   jsonb;
    v_item      jsonb;
    v_material  jsonb;
    v_limit     jsonb;
    v_section_id bigint;
    v_item_id    bigint;
    v_s_index    integer := 0;
    v_i_index    integer := 0;
    v_m_index    integer := 0;
    v_l_index    integer := 0;
    v_vat_percent numeric;
    v_vat_base    text;
    v_status      text;
    v_result      jsonb;
    v_work_client numeric := 0;
    v_work_worker numeric := 0;
    v_mat_client  numeric := 0;
    v_mat_purchase numeric := 0;
    v_limits      numeric := 0;
    v_subtotal    numeric := 0;
    v_vat         numeric := 0;
    v_items_count integer := 0;
begin
    if not public.rsk_is_estimate_editor() then
        raise exception 'Сметы доступны Администратору, Главному инженеру и Инженеру ПТО';
    end if;

    if p_payload is null then
        raise exception 'Пустой запрос: нечего сохранять';
    end if;

    -- Повтор уже выполненной команды: возвращаем прежний результат.
    if p_command_key is not null then
        select l.estimate_id into v_existing
          from public.estimate_command_log l
         where l.command_key = p_command_key;

        if v_existing is not null then
            select to_jsonb(e) into v_result
              from public.estimates e
             where e.id = v_existing;
            if v_result is not null then
                return v_result;
            end if;
        end if;
    end if;

    v_vat_percent := coalesce((p_payload->>'vat_percent')::numeric, 0);
    v_vat_base    := coalesce(nullif(p_payload->>'vat_base', ''), 'both');
    v_status      := coalesce(nullif(p_payload->>'status', ''), 'draft');

    if v_vat_base not in ('works', 'materials', 'both') then
        v_vat_base := 'both';
    end if;
    if v_status not in ('draft', 'approved', 'archived') then
        v_status := 'draft';
    end if;

    if p_estimate_id is null then
        perform pg_advisory_xact_lock(hashtext('freedom.estimates.number'));

        select coalesce(max(e.number_seq), 0) + 1
          into v_seq
          from public.estimates e
         where e.number_year = extract(year from now())::integer;

        v_year   := extract(year from now())::integer;
        v_number := lpad(v_seq::text, 5, '0') || '/' || v_year::text;

        insert into public.estimates (
            number, number_year, number_seq, title, object_name, project_id,
            client_id, notes, vat_percent, vat_base, status, created_by_employee_id
        ) values (
            v_number, v_year, v_seq,
            coalesce(nullif(p_payload->>'title', ''), 'Без названия'),
            nullif(p_payload->>'object_name', ''),
            nullif(p_payload->>'project_id', '')::bigint,
            nullif(p_payload->>'client_id', '')::bigint,
            nullif(p_payload->>'notes', ''),
            v_vat_percent, v_vat_base, v_status,
            public.rsk_current_employee_id()
        )
        returning id into v_id;
    else
        update public.estimates e
           set title       = coalesce(nullif(p_payload->>'title', ''), e.title),
               object_name = nullif(p_payload->>'object_name', ''),
               project_id  = nullif(p_payload->>'project_id', '')::bigint,
               client_id   = nullif(p_payload->>'client_id', '')::bigint,
               notes       = nullif(p_payload->>'notes', ''),
               vat_percent = v_vat_percent,
               vat_base    = v_vat_base,
               status      = v_status,
               updated_at  = now()
         where e.id = p_estimate_id
        returning e.id into v_id;

        if v_id is null then
            raise exception 'Смета не найдена: возможно, её удалили';
        end if;
    end if;

    -- Дети пересоздаются целиком: смета — документ, а не «журнал правок».
    -- Разделы удаляем каскадом (вместе с позициями и материалами позиций).
    delete from public.estimate_sections s where s.estimate_id = v_id;
    delete from public.estimate_limits l where l.estimate_id = v_id;

    for v_section in
        select value from jsonb_array_elements(coalesce(p_payload->'sections', '[]'::jsonb))
    loop
        insert into public.estimate_sections (estimate_id, name, order_index)
        values (v_id, coalesce(nullif(v_section->>'name', ''), 'Розділ'), v_s_index)
        returning id into v_section_id;

        v_s_index := v_s_index + 1;
        v_i_index := 0;

        for v_item in
            select value from jsonb_array_elements(coalesce(v_section->'items', '[]'::jsonb))
        loop
            insert into public.estimate_items (
                section_id, work_id, name, unit, quantity,
                price_worker, price_client, order_index
            ) values (
                v_section_id,
                nullif(v_item->>'work_id', '')::bigint,
                coalesce(nullif(v_item->>'name', ''), 'Позиція'),
                coalesce(nullif(v_item->>'unit', ''), 'шт'),
                coalesce((v_item->>'quantity')::numeric, 0),
                coalesce((v_item->>'price_worker')::numeric, 0),
                coalesce((v_item->>'price_client')::numeric, 0),
                v_i_index
            )
            returning id into v_item_id;

            v_i_index := v_i_index + 1;
            v_m_index := 0;

            for v_material in
                select value from jsonb_array_elements(coalesce(v_item->'materials', '[]'::jsonb))
            loop
                insert into public.estimate_item_materials (
                    item_id, material_id, name, unit, quantity, price_purchase,
                    price_client, consumption, is_customer_supplied, order_index
                ) values (
                    v_item_id,
                    nullif(v_material->>'material_id', '')::bigint,
                    coalesce(nullif(v_material->>'name', ''), 'Матеріал'),
                    coalesce(nullif(v_material->>'unit', ''), 'шт'),
                    coalesce((v_material->>'quantity')::numeric, 0),
                    coalesce((v_material->>'price_purchase')::numeric, 0),
                    coalesce((v_material->>'price_client')::numeric, 0),
                    nullif(v_material->>'consumption', '')::numeric,
                    coalesce((v_material->>'is_customer_supplied')::boolean, false),
                    v_m_index
                );

                v_m_index := v_m_index + 1;
            end loop;
        end loop;
    end loop;

    for v_limit in
        select value from jsonb_array_elements(coalesce(p_payload->'limits', '[]'::jsonb))
    loop
        insert into public.estimate_limits (estimate_id, name, percent, base, order_index)
        values (
            v_id,
            coalesce(nullif(v_limit->>'name', ''), 'Ліміт'),
            coalesce((v_limit->>'percent')::numeric, 0),
            case
                when coalesce(v_limit->>'base', '') in ('works', 'materials', 'both')
                    then v_limit->>'base'
                else 'both'
            end,
            v_l_index
        );

        v_l_index := v_l_index + 1;
    end loop;

    -- Журнал команды: повтор этого же ключа вернёт ту же смету.
    if p_command_key is not null then
        insert into public.estimate_command_log (command_key, estimate_id)
        values (p_command_key, v_id)
        on conflict (command_key) do nothing;
    end if;

    -- Итоги сметы: считаем в базе, чтобы список смет показывал суммы, не
    -- выгружая все позиции. Правила те же, что в js/modules/estimate-doc.js
    -- (количество материалов округляем вверх, давальческие не считаем) —
    -- менять их нужно вместе, иначе список и документ разойдутся.
    select
        coalesce(sum(coalesce(i.quantity, 0) * coalesce(i.price_client, 0)), 0),
        coalesce(sum(coalesce(i.quantity, 0) * coalesce(i.price_worker, 0)), 0),
        count(*)
      into v_work_client, v_work_worker, v_items_count
      from public.estimate_items i
      join public.estimate_sections s on s.id = i.section_id
     where s.estimate_id = v_id;

    select
        coalesce(sum(ceil(coalesce(m.quantity, 0)) * coalesce(m.price_client, 0)), 0),
        coalesce(sum(ceil(coalesce(m.quantity, 0)) * coalesce(m.price_purchase, 0)), 0)
      into v_mat_client, v_mat_purchase
      from public.estimate_item_materials m
      join public.estimate_items i on i.id = m.item_id
      join public.estimate_sections s on s.id = i.section_id
     where s.estimate_id = v_id
       and coalesce(m.is_customer_supplied, false) = false;

    select coalesce(sum(
             case l.base
                 when 'works' then v_work_client * l.percent / 100
                 when 'materials' then v_mat_client * l.percent / 100
                 else (v_work_client + v_mat_client) * l.percent / 100
             end), 0)
      into v_limits
      from public.estimate_limits l
     where l.estimate_id = v_id;

    v_subtotal := v_work_client + v_mat_client + v_limits;
    v_vat := case when v_vat_percent > 0 then v_subtotal * v_vat_percent / 100 else 0 end;

    update public.estimates e
       set total_client    = round(v_subtotal + v_vat, 2),
           total_materials = round(v_mat_client, 2),
           total_naryad    = round(v_work_worker + v_mat_purchase, 2),
           items_count     = v_items_count,
           updated_at      = now()
     where e.id = v_id;

    select to_jsonb(e) into v_result
      from public.estimates e
     where e.id = v_id;

    return v_result;
end $$;

revoke all on function public.save_estimate(jsonb, bigint, uuid) from public;
grant execute on function public.save_estimate(jsonb, bigint, uuid) to authenticated;

-- Удаление сметы. Разделы, позиции, материалы позиций и лимиты уходят
-- каскадом (внешние ключи с on delete cascade), поэтому чистить их вручную
-- не нужно — и нельзя забыть.
create or replace function public.delete_estimate(p_estimate_id bigint)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
    if not public.rsk_is_estimate_editor() then
        raise exception 'Сметы доступны Администратору, Главному инженеру и Инженеру ПТО';
    end if;

    delete from public.estimates e where e.id = p_estimate_id;

    if not found then
        raise exception 'Смета не найдена: возможно, её уже удалили';
    end if;

    return true;
end $$;

revoke all on function public.delete_estimate(bigint) from public;
grant execute on function public.delete_estimate(bigint) to authenticated;

-- Смена статуса сметы (черновик → утверждена → архив) отдельной командой:
-- статус переключают и из списка, а тащить ради этого всю смету в браузер
-- и обратно незачем.
create or replace function public.set_estimate_status(p_estimate_id bigint, p_status text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
    v_row jsonb;
begin
    if not public.rsk_is_estimate_editor() then
        raise exception 'Сметы доступны Администратору, Главному инженеру и Инженеру ПТО';
    end if;

    if p_status not in ('draft', 'approved', 'archived') then
        raise exception 'Неизвестный статус сметы: %', p_status;
    end if;

    update public.estimates e
       set status = p_status, updated_at = now()
     where e.id = p_estimate_id
    returning to_jsonb(e) into v_row;

    if v_row is null then
        raise exception 'Смета не найдена: возможно, её удалили';
    end if;

    return v_row;
end $$;

revoke all on function public.set_estimate_status(bigint, text) from public;
grant execute on function public.set_estimate_status(bigint, text) to authenticated;

commit;

-- =====================================================================
-- 11. САМОПРОВЕРКА
-- =====================================================================
-- SQL Editor останавливается на ПЕРВОЙ ошибке, а сообщения об ошибках видны
-- только на вкладке Notices. Поэтому файл заканчивается проверкой того, что
-- реально нужно приложению: 14 таблиц, включённый RLS, закрытая от anon
-- схема, закрытая ПРЯМАЯ запись в смету и пять команд с фиксированным
-- search_path. Строки 'ok' должны повторяться при каждом запуске файла.
do $$
declare
    v_list    text[] := array[
        'estimate_units', 'estimate_work_sections', 'estimate_material_sections',
        'estimate_works', 'estimate_materials', 'estimate_work_materials',
        'estimate_clients', 'estimate_company', 'estimates', 'estimate_sections',
        'estimate_items', 'estimate_item_materials', 'estimate_limits',
        'estimate_command_log'];
    v_names   text[] := array[
        'save_estimate', 'delete_estimate', 'set_estimate_status',
        'estimate_next_number', 'rsk_is_estimate_editor'];
    v_tables  integer;
    v_rls     integer;
    v_funcs   integer;
    v_paths   integer;
    v_anon    integer;
    v_writes  integer;
    v_dep     integer;
begin
    select count(*), count(*) filter (where c.relrowsecurity)
      into v_tables, v_rls
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      cross join unnest(v_list) as t(name)
     where n.nspname = 'public'
       and c.relkind = 'r'
       and c.relname = t.name;

    raise notice 'таблицы смет (справочники, смета, журнал): %',
        case when v_tables = 14 then 'ok'
             else 'MISSING - создано ' || v_tables || ' из 14 таблиц' end;

    raise notice 'RLS включён на таблицах смет: %',
        case when v_rls = 14 then 'ok'
             else 'MISSING - RLS включён на ' || v_rls || ' из 14 таблиц' end;

    select count(*) into v_anon
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      cross join unnest(v_list) as t(name)
     where n.nspname = 'public'
       and c.relkind = 'r'
       and c.relname = t.name
       and has_table_privilege('anon', c.oid, 'SELECT, INSERT, UPDATE, DELETE');

    raise notice 'таблицы смет закрыты от anon: %',
        case when v_anon = 0 then 'ok'
             else 'MISSING - anon имеет права на ' || v_anon || ' таблиц' end;

    select count(*) into v_writes
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      cross join unnest(v_list) as t(name)
     where n.nspname = 'public'
       and c.relkind = 'r'
       and c.relname = t.name
       and t.name in ('estimates', 'estimate_sections', 'estimate_items',
                      'estimate_item_materials', 'estimate_limits',
                      'estimate_command_log')
       and has_table_privilege('authenticated', c.oid, 'INSERT, UPDATE, DELETE');

    raise notice 'смета пишется только командами (прямой insert/update закрыт): %',
        case when v_writes = 0 then 'ok'
             else 'MISSING - прямая запись открыта на ' || v_writes || ' таблиц сметы' end;

    select count(*), count(*) filter (where p.proconfig is not null)
      into v_funcs, v_paths
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      cross join unnest(v_names) as t(name)
     where n.nspname = 'public'
       and p.proname = t.name;

    raise notice 'команды смет (сохранение, удаление, статус, номер, проверка права): %',
        case when v_funcs = 5 then 'ok'
             else 'MISSING - найдено ' || v_funcs || ' из 5 команд' end;

    raise notice 'у команд смет фиксированный search_path: %',
        case when v_paths = 5 then 'ok'
             else 'MISSING - search_path задан у ' || v_paths || ' из 5 команд' end;

    select count(*) into v_dep
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      cross join unnest(array[
          'rsk_current_employee_role', 'rsk_current_employee_id']) as t(name)
     where n.nspname = 'public'
       and p.proname = t.name;

    -- Обе функции берутся из v2.7.0: роль решает, кому открыт раздел, а id
    -- записывается автором сметы. Без второй смета не сохраняется вообще —
    -- и ошибка вылезала бы только при нажатии «Сохранить».
    raise notice 'зависимости v2.7.0 (роль и сотрудник): %',
        case when v_dep = 2 then 'ok'
             else 'MISSING - нет rsk_current_employee_role или rsk_current_employee_id: сначала примените database/migrate-v2.7-rls-finance.sql' end;
end $$;

-- PostgREST держит схему в кэше: без этого запрос к новой таблице ответит
-- «Could not find the table ... in the schema cache», пока не истечёт кэш.
-- Команда идёт ПОСЛЕДНЕЙ: всё, что создано после неё, в кэш API не попадёт.
notify pgrst, 'reload schema';
