-- =====================================================================
-- RSK ODESSA — СХЕМА БАЗЫ ДАННЫХ (РЕКОНСТРУКЦИЯ)
-- =====================================================================
-- ⚠️ ЭТО РЕКОНСТРУКЦИЯ ПО КОДУ, А НЕ ДАМП БОЕВОЙ БАЗЫ.
-- Файл собран по фактическому использованию таблиц и колонок во фронтенде
-- (js/database.js, js/modules/*.js): описано только то, что приложение
-- читает и пишет.
--
-- Здесь СОЗНАТЕЛЬНО НЕТ:
--   * политик RLS — они настраиваются в Supabase и должны проверяться отдельно;
--   * бакетов Storage: estimates, task-photos, receipts, project-files;
--   * индексов, триггеров и функций боевой базы. Индексы под страничные списки
--     (v2.9.0) лежат отдельным файлом: database/migrate-v2.9-scale-indexes.sql —
--     список индексов и связку «фильтр в коде ↔ индекс» стережёт
--     tools/checks/migration-check.mjs.
--
-- Перед применением сверьтесь с реальной БД: типы id, NOT NULL, значения
-- CHECK-констрейнтов (например project_files.category) и наличие связей
-- должны совпадать, иначе фронтенд получит другие ошибки.
--
-- Это полная схема вместе с изменениями версии v2.4.0 (счёт поставщика,
-- статус «Доставлено на объект», маркер source = 'financier_topup').
-- Если база уже развёрнута, применяйте не этот файл, а пошаговые миграции:
-- database/migrate-v2.4.sql (и предыдущие migrate-v*.sql по порядку).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Сотрудники
-- ---------------------------------------------------------------------
create table if not exists employees (
    id                    bigint generated by default as identity primary key,
    name                  text        not null,
    position              text        not null,   -- ключ из CONFIG.POSITIONS / ROLE_PERMISSIONS
    phone                 text,
    notes                 text,
    status                text        not null default 'active',  -- 'active' | 'blocked'
    user_id               uuid,                   -- auth.users.id (привязка аккаунта)
    deactivated_at        timestamptz,
    deactivation_reason   text,
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Объекты (строительные площадки)
-- ---------------------------------------------------------------------
create table if not exists projects (
    id                    bigint generated by default as identity primary key,
    name                  text        not null,
    foreman_id            bigint      references employees(id),
    estimate_file_path    text,                   -- путь в бакете estimates
    estimate_file_name    text,
    estimate_uploaded_at  timestamptz,
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Разделы сметы — они же строки графика работ (Gantt)
-- ---------------------------------------------------------------------
create table if not exists sections (
    id                    bigint generated by default as identity primary key,
    project_id            bigint      not null references projects(id),
    name                  text        not null,   -- ключ сопоставления при перезагрузке сметы
    plan_works            numeric     not null default 0,
    plan_materials        numeric     not null default 0,
    plan_total            numeric     not null default 0,
    planned_start_date    date,                   -- даты графика: смета их НЕ перезаписывает
    planned_end_date      date,
    actual_end_date       date,                   -- факт закрытия раздела
    closed_by_employee_id bigint      references employees(id),
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Заявки на материалы (нумерация «З-N/YY»)
-- ---------------------------------------------------------------------
-- status:
--   new         — новая (ждёт снабженца)
--   in_progress — в обработке (снабженец связался с поставщиком, загрузил счёт)
--   delivered   — доставлено на объект (позиции ушли в «Реестр материалов»)
--   closed      — legacy-закрытие закупки (до v2.4.0, в реестре учитывается)
--   archived    — архив
--
-- ⚠️ На боевой базе список значений status закрыт CHECK-ограничением
--    orders_status_check. Миграция v2.4.0 (БЛОК 4) снимает его и ставит
--    заново с этим же списком: без неё заявка не закрывается —
--    «new row for relation "orders" violates check constraint
--    "orders_status_check"» (в старом списке нет 'delivered').
--    Добавляете новый статус в код (js/config.js) — добавьте его и в
--    ограничение, иначе база отклонит запись.
--
-- payment_source:
--   company  — платит фирма по счёту (безнал). Деньги списываются НЕ с
--              подотчёта финансиста: он только отмечает счёт оплаченным;
--   employee — заплатил снабженец из своего подотчёта (создаётся расход).
--
-- payment_status: 'paid' — оплачено, 'debt' — «Ожидает оплаты»
-- (см. database/migrate-v2.4.sql, блок 1).
-- ---------------------------------------------------------------------
create table if not exists orders (
    id                      bigint generated by default as identity primary key,
    request_number          text        not null unique,          -- 'З-12/25'
    project_id              bigint      references projects(id),
    section_id              bigint      references sections(id),
    status                  text        not null default 'new',   -- new | in_progress | delivered | closed | archived
    desired_date            date,
    purchase_data           jsonb       not null default '{}'::jsonb,
    purchase_notes          text,
    created_by_employee_id  bigint      references employees(id),
    supplier                text,
    total_sum               numeric     not null default 0,
    payment_source          text        not null default 'company',  -- company | employee
    payer_employee_id       bigint      references employees(id),
    closed_at               timestamptz,
    -- --- v2.4.0: счёт поставщика и его оплата (migrate-v2.4.sql) ---
    invoice_path            text,                                 -- файл счёта в Storage (подпапка invoices/)
    invoice_file_name       text,                                 -- исходное имя файла (показываем в подсказке)
    invoice_uploaded_at     timestamptz,
    invoice_total           numeric,                              -- сумма по счёту (заполняет снабженец)
    payment_status          text        default 'paid',           -- paid | debt («Ожидает оплаты»)
    delivered_at            timestamptz,                          -- материалы приехали на объект
    paid_at                 timestamptz,                          -- счёт оплачен (это и есть «оплачено»)
    paid_by_employee_id     bigint      references employees(id),  -- кто из финансистов оплатил
    -- --- v2.5.0: НДС счёта и способ закрытия своей доставки (migrate-v2.5.sql) ---
    invoice_price_mode      text        not null default 'with_vat', -- with_vat | without_vat (как введены цены)
    invoice_vat_rate        numeric     not null default 0,          -- ставка НДС позиций счёта, %
    vat_total               numeric     not null default 0,          -- НДС по счёту (справочно, для бухгалтера)
    own_delivery_charge     text,                                    -- snagach | employee | firm (кто платит за свою доставку)
    own_delivery_employee_id bigint     references employees(id),    -- чей подотчёт списывается при charge = 'employee'
    own_delivery_vat_rate   numeric     not null default 0,          -- ставка НДС на услугу перевозки, %
    created_at              timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Позиции заявок на материалы
-- ---------------------------------------------------------------------
-- Доставка по заявке хранится отдельной позицией в order_items
-- (js/config.js → CONFIG.DELIVERY_ITEM, qty = 1, эмодзи 🚚 рисует интерфейс):
-- её вписывает снабженец в окне «🧾 Счёт поставщика». Отдельной колонки
-- в orders нет намеренно — иначе потребовалась бы миграция боевой базы.
--
-- Чья доставка — снабженец выбирает в том же окне:
--   * «Доставка» (delivery_kind = 'supplier') — везёт поставщик: сумма входит
--     в счёт (orders.invoice_total / total_sum);
--   * «Доставка компании» (delivery_kind = 'company') — везёт компания: в счёт
--     поставщика сумма НЕ входит (invoice_total — только материалы), но
--     остаётся строкой заявки, поэтому видна в «📊 Реестре материалов»
--     (категория «🚚 Доставка», колонка «Оплата» — «🏢 Вне счёта») и в
--     план-факте объекта как себестоимость.
--
-- Признак вида доставки хранится в колонке delivery_kind (v2.5.0). Имена
-- строк остались ключом совместимости для данных, созданных раньше, —
-- их читает js/utils.js → getDeliveryItemType(), поэтому переименование
-- «на ходу» по-прежнему недопустимо.
--
-- ⚠️ Своя доставка = одна сумма в одном месте. Если она оплачена из
--    подотчёта, приложение создаёт cash_operations (source = 'own_delivery',
--    category = 'delivery'), и тогда строка заявки из ДЕНЕГ больше не
--    считается (её исключают реестр, план-факт и дашборд) — иначе сумма
--    попала бы в итоги дважды. Пока расхода нет (charge = 'firm', то есть
--    платит фирма, либо счёт ещё не пересохранили), строка заявки — это и
--    есть себестоимость объекта. См. js/modules/orders.js →
--    saveOwnDeliveryExpense().
create table if not exists order_items (
    id              bigint generated by default as identity primary key,
    order_id        bigint  not null references orders(id),
    name            text    not null,
    unit            text,
    qty             numeric not null default 0,
    unit_price      numeric not null default 0,        -- цена к оплате, С НДС
    total_price     numeric not null default 0,        -- сумма к оплате, С НДС
    payment_status  text,                              -- 'paid' | 'debt' («Ожидает оплаты»)
    -- --- v2.5.0: НДС и вид доставки (migrate-v2.5.sql) ---
    vat_rate        numeric not null default 0,        -- ставка НДС позиции, %
    vat_amount      numeric not null default 0,        -- НДС внутри total_price, справочно
    price_with_vat  boolean not null default true,     -- цена введена уже с НДС?
    delivery_kind   text                               -- supplier | company (у обычных позиций NULL)
);

-- ---------------------------------------------------------------------
-- Заявки финансов на работы (нумерация «Ф-N/YY»)
-- ---------------------------------------------------------------------
create table if not exists cash_requests (
    id                        bigint generated by default as identity primary key,
    request_number            text        not null unique,        -- 'Ф-12/25'
    project_id                bigint      references projects(id),
    section_id                bigint      references sections(id),
    employee_id               bigint      not null references employees(id),
    total_sum                 numeric     not null default 0,
    comment                   text,
    -- pending  — ждёт решения директора
    -- approved — директор одобрил, ждёт выдачи финансистом
    -- revision — директор вернул автору на доработку (причина в rejection_reason)
    -- rejected — директор отказал (причина в rejection_reason)
    -- issued   — деньги выданы, подотчёт получателя пополнен
    -- archived — автор убрал законченную заявку со своего рабочего экрана
    -- ⚠️ CHECK-констрейнта на список значений в боевой базе может не быть;
    --    статус «revision» появился в v2.2.0, «archived» — в v2.6.0. Миграция
    --    КОЛОНОК для них не нужна (новые значения пишутся в существующую
    --    text-колонку), но если ограничение на статусы в базе ЕСТЬ, его надо
    --    обновить — иначе база отклонит запись с ошибкой
    --    cash_requests_status_check (SQLSTATE 23514): database/migrate-v2.6.sql.
    status                    text        not null default 'pending', -- pending|approved|revision|rejected|issued|archived
    approved_by_employee_id   bigint      references employees(id),
    approved_at               timestamptz,
    -- Причина отказа ИЛИ причина возврата на доработку — что именно, видно
    -- по status заявки. Отдельной колонки revision_reason нет намеренно:
    -- лишняя колонка потребовала бы миграции боевой базы.
    rejection_reason          text,
    issued_operation_id       bigint,   -- FK на cash_operations (добавляется ниже)
    created_at                timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Позиции заявок финансов
-- ---------------------------------------------------------------------
create table if not exists cash_request_items (
    id           bigint generated by default as identity primary key,
    request_id   bigint  not null references cash_requests(id),
    name         text    not null,
    unit         text,
    qty          numeric not null default 0,
    unit_price   numeric not null default 0,
    total_price  numeric not null default 0
);

-- ---------------------------------------------------------------------
-- Кассовые операции (подотчёт: выдача / расход / возврат)
-- ---------------------------------------------------------------------
-- Приложение использует четыре типа операций:
--   issue      — выдача подотчёта сотруднику (баланс растёт), в том числе
--                пополнение подотчёта финансиста директором;
--   expense    — расход сотрудника (баланс падает), попадает в «Реестр»;
--   return     — возврат в кассу (баланс падает). Этим же типом оформляется
--                выдача денег ФИНАНСИСТОМ по заявке: сумма списывается с его
--                подотчёта и зачисляется получателю операцией issue.
--                Отдельный тип 'transfer' не вводится специально: представление
--                employee_cash_balance знает только issue/expense/return,
--                а expense попал бы в «Реестр» как реальная трата, хотя
--                выданный подотчёт тратой ещё не является;
--   adjustment — корректировка (в коде считается приходом).
--
-- Маркер source (v2.4.0 → v2.5.0):
--   'manual'          — операция из формы «Внести расход»;
--   'order'           — расход, созданный при закрытии заявки на материалы
--                       (снабженец заплатил из подотчёта; операция несёт все
--                       позиции заявки);
--   'own_delivery'    — своя доставка (v2.5.0): заявку везла компания, а
--                       деньги списали с подотчёта снабженца (или другого
--                       сотрудника). Категория — 'delivery', order_id — та
--                       же заявка. По этой метке реестр и план-факт понимают,
--                       что строку доставки заявки считать НЕ надо: сумма
--                       уже в расходе (js/modules/orders.js →
--                       saveOwnDeliveryExpense());
--   'financier_topup' — директор передал деньги в подотчёт финансиста.
--     Именно по этому маркеру строится «Ведомость пополнений подотчёта
--     финансиста» (js/modules/cash.js → openFinancierTopUpStatement).
--     Операции, созданные до v2.4.0, распознаются по описанию («Передал…»),
--     старое значение 'manual' тоже поддерживается.
-- ---------------------------------------------------------------------
create table if not exists cash_operations (
    id              bigint generated by default as identity primary key,
    employee_id     bigint  not null references employees(id),
    operation_type  text    not null,                 -- issue | expense | return
    amount          numeric not null default 0,
    description     text,                             -- в формах это «Комментарий»
    category        text,                             -- категория расхода
    items           jsonb   not null default '[]'::jsonb,  -- [{name, unit, qty, unit_price, total_price}]
    project_id      bigint  references projects(id),
    section_id      bigint  references sections(id),
    order_id        bigint  references orders(id),    -- если расход создан при закрытии заявки
    source          text,                             -- 'manual' | 'order' | 'financier_topup' | 'own_delivery'
    receipt_path    text,                             -- путь в бакете receipts
    -- --- v2.5.0: НДС расхода (migrate-v2.5.sql) ---
    vat_rate        numeric not null default 0,       -- ставка НДС, %
    vat_amount      numeric not null default 0,       -- НДС внутри amount, справочно
    operation_date  date    not null default current_date,
    created_by      uuid,                             -- auth.users.id
    created_at      timestamptz not null default now()
);

alter table cash_requests
    drop constraint if exists cash_requests_issued_operation_id_fkey;

alter table cash_requests
    add constraint cash_requests_issued_operation_id_fkey
    foreign key (issued_operation_id) references cash_operations(id);

-- ---------------------------------------------------------------------
-- Задачи
-- ---------------------------------------------------------------------
create table if not exists tasks (
    id                    bigint generated by default as identity primary key,
    title                 text    not null,
    description           text,
    project_id            bigint  references projects(id),
    section_id            bigint  references sections(id),
    author_employee_id    bigint  references employees(id),
    assignee_employee_id  bigint  references employees(id),
    priority              text    not null default 'normal',
    deadline              date,
    status                text    not null default 'pending',  -- pending|in_progress|done|cancelled
    photo_path            text,                       -- путь в бакете task-photos
    comments              jsonb   not null default '[]'::jsonb,  -- [{text, author, author_id, date}]
    history               jsonb   not null default '[]'::jsonb,
    completed_at          timestamptz,
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Файлы объектов (документация)
-- ---------------------------------------------------------------------
create table if not exists project_files (
    id                       bigint generated by default as identity primary key,
    project_id               bigint not null references projects(id),
    file_path                text   not null,          -- путь в бакете project-files
    file_name                text   not null,
    file_size                bigint,
    mime_type                text,
    category                 text   default 'project', -- project|photo|other|document|drawing
    description              text,
    uploaded_by_employee_id  bigint references employees(id),
    created_at               timestamptz not null default now()
);

-- =====================================================================
-- ПРЕДСТАВЛЕНИЕ: баланс подотчёта по сотрудникам
-- =====================================================================
-- Приложение читает его как таблицу employee_cash_balance
-- (фильтр по employee_id, сортировка по name).
-- =====================================================================
create or replace view employee_cash_balance as
select
    e.id   as employee_id,
    e.name as name,
    coalesce(sum(
        case
            when o.operation_type = 'issue'   then  o.amount
            when o.operation_type = 'expense' then -o.amount
            when o.operation_type = 'return'  then -o.amount
            else 0
        end
    ), 0)::numeric as balance
from employees e
left join cash_operations o on o.employee_id = e.id
group by e.id, e.name;

-- =====================================================================
-- ПРЕДСТАВЛЕНИЕ: строки «Реестра материалов» (v2.9.0)
-- =====================================================================
-- Одна строка вида = одна строка таблицы раздела «📊 Реестр»: позиция заявки,
-- оплаченной фирмой, или позиция расхода кассы (у расхода без позиций — сам
-- расход). Раздел читает их СТРАНИЦЕЙ (js/modules/registry.js →
-- db.selectPage('registry_rows', …)), а не всей таблицей.
--
-- Полное определение — database/migrate-v2.9-registry-view.sql (это файл,
-- который применяют в SQL Editor). Здесь состав, чтобы схему можно было
-- прочитать целиком:
--
--   kind           order | order_employee | own_delivery | expense — пометка строки
--   source_number  номер заявки или «💰 Расход»
--   order_id, row_key, entry_at, entry_date — источник, ключ строки и дата
--                  (заявки: delivered_at || closed_at || created_at;
--                   расходы: operation_date)
--   name, unit, qty, unit_price, total_sum, vat_amount
--   category       materials | works | delivery | other
--   payment        paid | debt («Ожидает оплаты») | company («🏢 Вне счёта»)
--   supplier, project_id, project_name, section_id, section_name,
--   employee_id, employee_name
--
-- ⚠️ security_invoker = true. Без этого вид выполнялся бы от имени владельца и
--    ОБХОДИЛ RLS: сотрудник увидел бы расходы всех объектов, хотя политика
--    rsk_cash_operations_select пускает к полному реестру только Администратора,
--    Директора, Главного инженера, Снабженца, Инженера ПТО и Финансиста
--    (database/migrate-v2.7-rls-finance.sql). Права на чтение вида выданы роли
--    authenticated, анонимному ключу — нет.
-- ⚠️ Своя доставка, уже оплаченная из подотчёта (cash_operations.source =
--    'own_delivery'), попадает в реестр РАСХОДОМ, а строка заявки («Доставка
--    компании») из вида исключается: иначе одна сумма считалась бы дважды.
--
-- Итог по ВСЕМУ отфильтрованному набору (а не по видимой странице) считает
-- команда public.registry_totals(p_project_id, p_section_id, p_category,
-- p_payment, p_employee_id, p_date_from, p_date_to) → rows_count, total_sum,
-- total_vat. Вспомогательные функции вида — public.rsk_delivery_kind(text, text)
-- (та же логика, что в js/utils.js → getDeliveryItemType) и
-- public.rsk_json_amount(jsonb, text) (разбор чисел из позиций расхода).
-- =====================================================================

-- =====================================================================
-- СВЯЗИ, которые ожидает фронтенд
-- =====================================================================
--   sections.project_id            -> projects.id
--   orders.project_id / section_id -> projects.id / sections.id
--   order_items.order_id           -> orders.id
--   cash_requests.employee_id      -> employees.id
--   cash_request_items.request_id  -> cash_requests.id
--   cash_operations.employee_id    -> employees.id
--   tasks.project_id / section_id  -> projects.id / sections.id
--   project_files.project_id       -> projects.id
--
-- Каскадное удаление объекта приложение делает само, последовательно
-- (js/modules/projects.js → confirmDeleteProject): сначала файлы в Storage,
-- затем позиции заявок, потом заявки/задачи/расходы/разделы и только
-- потом сам объект. Полагаться только на ON DELETE CASCADE нельзя.
--
-- БЕЗОПАСНОСТЬ: включите RLS на всех таблицах и напишите политики по ролям
-- (employees.position). Фронтенд прячет кнопки, но данные не защищает.


