-- =====================================================================
-- RSK ODESSA — СХЕМА БАЗЫ ДАННЫХ (РЕКОНСТРУКЦИЯ)
-- =====================================================================
-- ⚠️ ЭТО РЕКОНСТРУКЦИЯ ПО КОДУ, А НЕ ДАМП БОЕВОЙ БАЗЫ.
-- Файл собран по фактическому использованию таблиц и колонок во фронтенде
-- (js/database.js, js/modules/*.js): описано только то, что приложение
-- читает и пишет.
--
-- Здесь СОЗНАТЕЛЬНО НЕТ:
--   * политик RLS — они настраиваются в Supabase и должны проверяться отдельно;
--   * бакетов Storage: estimates, task-photos, receipts, project-files;
--   * индексов, триггеров и функций боевой базы.
--
-- Перед применением сверьтесь с реальной БД: типы id, NOT NULL, значения
-- CHECK-констрейнтов (например project_files.category) и наличие связей
-- должны совпадать, иначе фронтенд получит другие ошибки.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Сотрудники
-- ---------------------------------------------------------------------
create table if not exists employees (
    id                    bigint generated by default as identity primary key,
    name                  text        not null,
    position              text        not null,   -- ключ из CONFIG.POSITIONS / ROLE_PERMISSIONS
    phone                 text,
    notes                 text,
    status                text        not null default 'active',  -- 'active' | 'blocked'
    user_id               uuid,                   -- auth.users.id (привязка аккаунта)
    deactivated_at        timestamptz,
    deactivation_reason   text,
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Объекты (строительные площадки)
-- ---------------------------------------------------------------------
create table if not exists projects (
    id                    bigint generated by default as identity primary key,
    name                  text        not null,
    foreman_id            bigint      references employees(id),
    estimate_file_path    text,                   -- путь в бакете estimates
    estimate_file_name    text,
    estimate_uploaded_at  timestamptz,
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Разделы сметы — они же строки графика работ (Gantt)
-- ---------------------------------------------------------------------
create table if not exists sections (
    id                    bigint generated by default as identity primary key,
    project_id            bigint      not null references projects(id),
    name                  text        not null,   -- ключ сопоставления при перезагрузке сметы
    plan_works            numeric     not null default 0,
    plan_materials        numeric     not null default 0,
    plan_total            numeric     not null default 0,
    planned_start_date    date,                   -- даты графика: смета их НЕ перезаписывает
    planned_end_date      date,
    actual_end_date       date,                   -- факт закрытия раздела
    closed_by_employee_id bigint      references employees(id),
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Заявки на материалы (нумерация «З-N/YY»)
-- ---------------------------------------------------------------------
create table if not exists orders (
    id                      bigint generated by default as identity primary key,
    request_number          text        not null unique,          -- 'З-12/25'
    project_id              bigint      references projects(id),
    section_id              bigint      references sections(id),
    status                  text        not null default 'new',   -- new | in_progress | closed | archived
    desired_date            date,
    purchase_data           jsonb       not null default '{}'::jsonb,
    purchase_notes          text,
    created_by_employee_id  bigint      references employees(id),
    supplier                text,
    total_sum               numeric     not null default 0,
    payment_source          text        not null default 'company',  -- company | employee
    payer_employee_id       bigint      references employees(id),
    closed_at               timestamptz,
    created_at              timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Позиции заявок на материалы
-- ---------------------------------------------------------------------
create table if not exists order_items (
    id              bigint generated by default as identity primary key,
    order_id        bigint  not null references orders(id),
    name            text    not null,
    unit            text,
    qty             numeric not null default 0,
    unit_price      numeric not null default 0,
    total_price     numeric not null default 0,
    payment_status  text                                           -- 'paid' при создании
);

-- ---------------------------------------------------------------------
-- Заявки финансов на работы (нумерация «Ф-N/YY»)
-- ---------------------------------------------------------------------
create table if not exists cash_requests (
    id                        bigint generated by default as identity primary key,
    request_number            text        not null unique,        -- 'Ф-12/25'
    project_id                bigint      references projects(id),
    section_id                bigint      references sections(id),
    employee_id               bigint      not null references employees(id),
    total_sum                 numeric     not null default 0,
    comment                   text,
    -- pending  — ждёт решения директора
    -- approved — директор одобрил, ждёт выдачи финансистом
    -- revision — директор вернул автору на доработку (причина в rejection_reason)
    -- rejected — директор отказал (причина в rejection_reason)
    -- issued   — деньги выданы, подотчёт получателя пополнен
    -- ⚠️ CHECK-констрейнта на список значений в боевой базе может не быть;
    --    статус «revision» появился в v2.2.0 — миграция колонок НЕ нужна,
    --    новые значения пишутся в существующие text-колонки.
    status                    text        not null default 'pending', -- pending|approved|revision|rejected|issued
    approved_by_employee_id   bigint      references employees(id),
    approved_at               timestamptz,
    -- Причина отказа ИЛИ причина возврата на доработку — что именно, видно
    -- по status заявки. Отдельной колонки revision_reason нет намеренно:
    -- лишняя колонка потребовала бы миграции боевой базы.
    rejection_reason          text,
    issued_operation_id       bigint,   -- FK на cash_operations (добавляется ниже)
    created_at                timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Позиции заявок финансов
-- ---------------------------------------------------------------------
create table if not exists cash_request_items (
    id           bigint generated by default as identity primary key,
    request_id   bigint  not null references cash_requests(id),
    name         text    not null,
    unit         text,
    qty          numeric not null default 0,
    unit_price   numeric not null default 0,
    total_price  numeric not null default 0
);

-- ---------------------------------------------------------------------
-- Кассовые операции (подотчёт: выдача / расход / возврат)
-- ---------------------------------------------------------------------
-- Приложение использует четыре типа операций:
--   issue      — выдача подотчёта сотруднику (баланс растёт), в том числе
--                пополнение подотчёта финансиста директором;
--   expense    — расход сотрудника (баланс падает), попадает в «Реестр»;
--   return     — возврат в кассу (баланс падает). Этим же типом оформляется
--                выдача денег ФИНАНСИСТОМ по заявке: сумма списывается с его
--                подотчёта и зачисляется получателю операцией issue.
--                Отдельный тип 'transfer' не вводится специально: представление
--                employee_cash_balance знает только issue/expense/return,
--                а expense попал бы в «Реестр» как реальная трата, хотя
--                выданный подотчёт тратой ещё не является;
--   adjustment — корректировка (в коде считается приходом).
-- ---------------------------------------------------------------------
create table if not exists cash_operations (
    id              bigint generated by default as identity primary key,
    employee_id     bigint  not null references employees(id),
    operation_type  text    not null,                 -- issue | expense | return
    amount          numeric not null default 0,
    description     text,                             -- в формах это «Комментарий»
    category        text,                             -- категория расхода
    items           jsonb   not null default '[]'::jsonb,  -- [{name, unit, qty, unit_price, total_price}]
    project_id      bigint  references projects(id),
    section_id      bigint  references sections(id),
    order_id        bigint  references orders(id),    -- если расход создан при закрытии заявки
    source          text,                             -- 'manual' | 'order'
    receipt_path    text,                             -- путь в бакете receipts
    operation_date  date    not null default current_date,
    created_by      uuid,                             -- auth.users.id
    created_at      timestamptz not null default now()
);

alter table cash_requests
    drop constraint if exists cash_requests_issued_operation_id_fkey;

alter table cash_requests
    add constraint cash_requests_issued_operation_id_fkey
    foreign key (issued_operation_id) references cash_operations(id);

-- ---------------------------------------------------------------------
-- Задачи
-- ---------------------------------------------------------------------
create table if not exists tasks (
    id                    bigint generated by default as identity primary key,
    title                 text    not null,
    description           text,
    project_id            bigint  references projects(id),
    section_id            bigint  references sections(id),
    author_employee_id    bigint  references employees(id),
    assignee_employee_id  bigint  references employees(id),
    priority              text    not null default 'normal',
    deadline              date,
    status                text    not null default 'pending',  -- pending|in_progress|done|cancelled
    photo_path            text,                       -- путь в бакете task-photos
    comments              jsonb   not null default '[]'::jsonb,  -- [{text, author, author_id, date}]
    history               jsonb   not null default '[]'::jsonb,
    completed_at          timestamptz,
    created_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Файлы объектов (документация)
-- ---------------------------------------------------------------------
create table if not exists project_files (
    id                       bigint generated by default as identity primary key,
    project_id               bigint not null references projects(id),
    file_path                text   not null,          -- путь в бакете project-files
    file_name                text   not null,
    file_size                bigint,
    mime_type                text,
    category                 text   default 'project', -- project|photo|other|document|drawing
    description              text,
    uploaded_by_employee_id  bigint references employees(id),
    created_at               timestamptz not null default now()
);

-- =====================================================================
-- ПРЕДСТАВЛЕНИЕ: баланс подотчёта по сотрудникам
-- =====================================================================
-- Приложение читает его как таблицу employee_cash_balance
-- (фильтр по employee_id, сортировка по name).
-- =====================================================================
create or replace view employee_cash_balance as
select
    e.id   as employee_id,
    e.name as name,
    coalesce(sum(
        case
            when o.operation_type = 'issue'   then  o.amount
            when o.operation_type = 'expense' then -o.amount
            when o.operation_type = 'return'  then -o.amount
            else 0
        end
    ), 0)::numeric as balance
from employees e
left join cash_operations o on o.employee_id = e.id
group by e.id, e.name;

-- =====================================================================
-- СВЯЗИ, которые ожидает фронтенд
-- =====================================================================
--   sections.project_id            -> projects.id
--   orders.project_id / section_id -> projects.id / sections.id
--   order_items.order_id           -> orders.id
--   cash_requests.employee_id      -> employees.id
--   cash_request_items.request_id  -> cash_requests.id
--   cash_operations.employee_id    -> employees.id
--   tasks.project_id / section_id  -> projects.id / sections.id
--   project_files.project_id       -> projects.id
--
-- Каскадное удаление объекта приложение делает само, последовательно
-- (js/modules/projects.js → confirmDeleteProject): сначала файлы в Storage,
-- затем позиции заявок, потом заявки/задачи/расходы/разделы и только
-- потом сам объект. Полагаться только на ON DELETE CASCADE нельзя.
--
-- БЕЗОПАСНОСТЬ: включите RLS на всех таблицах и напишите политики по ролям
-- (employees.position). Фронтенд прячет кнопки, но данные не защищает.


